name: gorba_bot_web

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: gorba_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "${API_PORT:-18000}:8000"
    networks:
      - gorba_net

  payment-page:
    build:
      context: .
      dockerfile: Dockerfile.payment
    container_name: gorba_payment_page
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "${PAYMENT_API_PORT:-18001}:8001"
    networks:
      - gorba_net

networks:
  gorba_net:
    name: gorba_net
    external: true
